### ISSUE TITLE
When enabled it causes compatibility issues with Country Flags extension

### ISSUE THREAD

**Issue by forkless** [Crizz0/phpbb-ext-maxwidth-switch#8]
When full/fluid width is enabled the extension is causing an overlapping inline block (1px) inside the well area of National Flags footer.

**Comment by Crizz0** [comment]
Hi,

can you give me a image of the problem and a link to this other extension?

**Comment by Galixte** [comment]
Hi,

this extension: https://github.com/RMcGirr83/phpBB-3.1-nationalflags & flags images: https://github.com/RMcGirr83/phpBB-3.1-nationalflags/tree/master/flags

**Comment by Elsensee** [comment]
Not the flag images.. An image of the issue which occurs would be nice. :)

**Comment by Galixte** [comment]
Oh sorry ;)

**Comment by Crizz0** [comment]
@forkless What about more input?
